name: Tool Shortcut Sign Binary

on:
  push:
    branches:
      - tool/shortcut-sign-bin
    paths:
      - '.github/workflows/tool-shortcut-sign-bin.yml'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Download shortcut-sign
        run: |
          curl -L --fail --silent --show-error \
            -o shortcut-sign \
            https://github.com/0xilis/shortcut-sign/releases/download/v1.0.0-beta.5/shortcut-sign-linux-x86_64
          chmod +x shortcut-sign
          ./shortcut-sign version
          sha256sum shortcut-sign
      - uses: actions/upload-artifact@v4
        with:
          name: shortcut-sign-linux-x86_64
          path: shortcut-sign
          retention-days: 1
